### ISSUE TITLE
The state byte string 0x81

### ISSUE THREAD

**Issue by bdraco** [8none1/zengge_lednetwf#1]
https://github.com/8none1/zengge_lednetwf/blob/f2d9fa555752c16cbf567aead43608fa68d9060e/ledwf_controller.py#L80

Looks like
https://github.com/Danielhiversen/flux_led/blob/56cf8b57abc7c1a4e372361c653c7824e4cfc052/flux_led/protocol.py#L246

**Comment by 8none1** [comment]
It does look very similar, thanks for the tip off.

I intend to add support to `flux_led` but haven't got round to it yet.  I don't think it's especially hard, but there are quite a number of threads to unweave first.
