### ISSUE TITLE
Home Assistant Support

### ISSUE THREAD

**Issue by rgtkd** [8none1/zengge_lednetwf#2]
Hello, Is the MQTT for home assistant support still being worked on? Great job decoding this!

**Comment by DIYtechie** [comment]
+1 👍🏻

**Comment by 8none1** [comment]
I’m sorry to say that I haven’t looked at it in any depth. One has to use the Python async stuff and I have to learn it first. If anyone would like to take a crack at it feel free to take what you need from here. I’ll happily help.

**Comment by 8none1** [comment]
To build on the above a little more; I think the best way to build support for Home Assistant is to leverage the `led_ble` support in HA: 
https://github.com/home-assistant/core/tree/dev/homeassistant/components/led_ble

I seem to remember that this has some dependices on Flux LED too:
https://github.com/Danielhiversen/flux_led

Last time I looked at this it boggled my brain, so I didn't spend much time trying to understand it.

What I've done in the past is build a simple ESP32 set up which listens on MQTT and translates in to BT LE, see:
https://github.com/8none1/nimble_triones

Personally, I think that is easier and will probably be where I focus my efforts.

**Comment by 8none1** [comment]
I tried to work out how to add support to FluxLED and LED BLE, but it was too confusing. 

Check out this project though:  https://github.com/raulgbcr/lednetwf_ble
