### ISSUE TITLE
Home Assistant native support

### ISSUE THREAD

**Issue by raulgbcr** [8none1/zengge_lednetwf#5]
Hello! Just wanted to thank you for the awesome work you did here!

I've made a custom integration for home assistant that uses your work, check out at:

https://github.com/raulgbcr/lednetwf_ble

Right now it supports turning on/off, RGB colors and white color modes. I'm not sure if the effects part will be integrated in the future, since there is a ton of effects on this and I really don't have use for them. 

Hope its usefull for someone other than me. Thanks again!

**Comment by 8none1** [comment]
WOW!!!  This is fantastic, well done!

I'll add a link to your project from the README here, and I will get your project installed here and see if I can contribute anything.

Awesome stuff!  :tada:

**Comment by DIYtechie** [comment]
Awesome, can’t wait to try it! 🙏🏻🥳

**Comment by 8none1** [comment]
Raul's project is pretty much feature complete now and should be in HACS fairly soon.  Closing this.
